name: learning-actions
run-name: actions

on: [push]
jobs:
  using-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run script file
        working-directory: ${{ github.workspace }}/public
        run: |
            chmod +x ./run.sh
            ./public/run.sh
        shell: bash